### ISSUE TITLE
please merge the fix from 1.0.2-a to master

### ISSUE THREAD

**Issue by vkurland** [codeminders/socket.io-server-java#11]
I am still getting this exception with the latest 1.0.5 from master:

```
java.lang.NullPointerException
        at com.codeminders.socketio.server.Session.forcePollingCycle(Session.java:494)
        at com.codeminders.socketio.server.Session.onPacket(Session.java:300)
        at com.codeminders.socketio.server.transport.XHRTransportConnection.handle(XHRTransportConnection.java:78)
        at com.codeminders.socketio.server.transport.AbstractHttpTransport.handle(AbstractHttpTransport.java:68)
        at com.codeminders.socketio.server.SocketIOServlet.serve(SocketIOServlet.java:146)
        at com.codeminders.socketio.server.SocketIOServlet.doPost(SocketIOServlet.java:106)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:308)
```

**Comment by alexsaveliev** [comment]
done, my bad
